default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'fno'
  save_model_path: '/scratch/julian/neuralop/ks_models/pygen_quarter_res.pth'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  fno:
    data_channels: 1
    out_channels: 1
    n_modes: [128]
    hidden_channels: 128
    projection_channel_ratio: 4
    n_layers: 4
    domain_padding: None #0.078125
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: None
    skip: 'linear'
    implementation: 'reconstructed'

    use_channel_mlp: 1
    channel_mlp_expansion: 0.5
    channel_mlp_dropout: 0

    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False
    stabilizer: None # or 'tanh'

  # Optimizer
  opt:
    n_epochs: 50
    learning_rate: 2e-3
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 100
    gamma: 0.5

  # Dataset related
  data:
    folder: '/scratch/julian/neuralop/'
    file: 'pygen_1200_512_2000_20_201.06.pth'
    batch_size: 512
    n_train: 400
    data_start: 500
    coarsen_factor: 4
    train_resolution: 128
    n_tests: [50]
    test_resolutions: [128]
    test_batch_sizes: [128]
    encode_input: True
    encode_output: False
    architecture:
      dt: 0.25
      modes: 20
      T: 2000
      n_samples: 1200
      n_points: 128
      l: 201.06192982974676 # 2 * np.pi * 32
      width: 128

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: True

  # Weights and biases
  wandb:
    log: True
    name: None # If None, config will be used but you can override it here
    group: '' 
    project: "KS-Equation"
    entity: "jschmitt-reusebi" # put your username here
    sweep: False
    log_output: True
    eval_interval: 1